# abstract {#astmh}

## Title:

<!-- 
Towards standardized malaria serological surveillance:
A reproducible workflow
previous to the application of serology-based modeling

A reproducible workflow for the 
standardization of 
high-throughput ELISA experiments

A standarization of high-throughput ELISA experiments/assays
previous to the application of serological surveillance modeling

BERKELEY BOOK 2017
https://www.practicereproducibleresearch.org/

-->

**Towards reproducible malaria sero-surveillance:
A workflow for high-throughput ELISA plate standardization using R**

## Abstract:
@WHOreport2016
@elliott2014surveillance
@Seplveda2015
@CienciaReproducible2016

### Introduction

intro sentence:

- sero-surveillance or seroepidemiological studies
- antibody data is an excellent indicator of malaria exposure, transmission and 
immunity at population levels. 

Known field achievement:

- antigen selection
- mathematical models to define seropositivity, and changes in transmission and exposure.

Problem:

- No common procedure to standardize ELISA plates among publications
- Usage of privative softwares without workflow recording
- Lack of reproducibility of studies

Solution:

- Reproducible workflow for ELISA plates standardization
- Adds standard analysis tools to develop high-throughput assays
- Optimize sero-surveillance development

### Methods

- Plate protocol by @Miura2008
- Data input with `XLConnect` @XLConnect
- 4 parameter log-logistic regression with `drc` @Ritz2015
- Unbiased selection and Filtering of replicated reads across plates.

### Results

- residual variance homogenization of regression models per plate.
- Inter and Intra-plate Coefficients of variation for QC.

### Discussion

This type of reports, relevant for malaria surveillance [@elliott2014surveillance], 
would be highly improved with standardize open-acess lab/comp protocols

- Data input `plater` @plater
- Availability in GitHub

- Improve collaboration
- Standardize data generation and analysis methods will improve data comparison 
between populations and geographical regions

## Possible meetings

### August -> October (no AWARD)
- https://meetings.cshl.edu/meetings.aspx?meet=DATA&year=16

### January -> May (with TRAVEL AWARD)
- http://www.immunology2017.org/abstracts/

### April -> November
- http://www.astmh.org/annual-meeting

### April -> July
- http://symposium.iscbsc.org/

### September -> December (with SCI AWARD)
- http://www.syndromic.org/annual-conference/2016-isds-conference
<!--## References-->
