---
title: "revcatr"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

# VIGNETTE

## cross-sectional

R function for maximum likelihood estimation of a reversible catalytic model fit to
cross-sectional data, using an example from Williams [10].

```{r}
Lccm1 <- function(theta,data) {
  
  # theta : vector of length two, including h, r (parameters to be maximized)
  # h = seroconversion rate, r = seroreversion rate
  # (to maximize over a single parameter, e.g. h, replace theta with
  # separate args for h and r and pass an r value to the function)
  # data : data frame with columns = age / n / k

  h <- rep(theta[1],nrow(data)) #incidence rate
  r <- rep(theta[2],nrow(data)) #recovery rate
  t <- data[,1] #time(age strata)
  n <- data[,2] #number tested
  k <- data[,3] #number positive
  
  # probability of infection in time t
  p <- h/(r+h)*(1-exp(-(r+h)*t)) 
  
  # negative log likelihood function
  sum( - (k)*log(p) - (n-k)*log(1-p) )

  }
```

```{r}
Lccm1c <- function(theta, r,data) {
  
  # theta : vector of length two, including h, r (parameters to be maximized)
  # h = seroconversion rate, r = seroreversion rate
  # (to maximize over a single parameter, e.g. h, replace theta with
  # separate args for h and r and pass an r value to the function)
  # data : data frame with columns = age / n / k

  h <- rep(theta,nrow(data)) #incidence rate
  r <- rep(r,nrow(data)) #recovery rate
  t <- data[,1] #time(age strata)
  n <- data[,2] #number tested
  k <- data[,3] #number positive
  
  # probability of infection in time t
  p <- h/(r+h)*(1-exp(-(r+h)*t)) 
  
  # negative log likelihood function
  sum( - (k)*log(p) - (n-k)*log(1-p) )

  }
```

```{r}
#?profile
Lccm2 <- function(theta, data, r, u) {
  
  # theta : vector of length one, including h, r (parameters to be maximized)
  #         h = seroconversion rate, r = seroreversion rate
  #         (to maximize over a single parameter, e.g. h, replace theta with
  #         separate args for h and r and pass an r value to the function)
  # data : data frame with columns = age / n / k

  h <- rep(theta[1],nrow(data)) #incidence rate
  r <- rep(r,nrow(data)) #recovery rate
  x <- h/(r+h)
  y <- h + r
  t <- data[,1] #time(age strata)
  n <- data[,2] #number tested
  k <- data[,3] #number positive
  
  # probability of infection in time t
  p <- h/(r+h)*(1-exp(-(r+h)*t)) 
  
  # negative log likelihood function
  sum( - (k)*log(p) - (n-k)*log(1-p) )

  }
```

## data: both estimates

```{r}
# data from Table 2 of Williams 1994

dog <- data.frame(
  age=c(3.71,10.76,21.00,38.89,64.07,106.82),
  n=c(100,74,114,110,55,27),
  k=c(14,30,63,59,37,14)
  )

# add proportion positive
library(tidyverse)
dog <- dog %>% mutate(p= k/n)

# MLE solution
dogll <- optim(c(0.1,0.1),fn=Lccm1,data=dog,hessian=TRUE)
dogll
#summary(dogll)
#?optim
```

```{r}
dogll$par
sqrt(diag(solve(dogll$hessian)))
sqrt(abs(diag(solve(dogll$hessian))))
```

```{r}
# confidence intervals

#https://stats.stackexchange.com/questions/27033/in-r-given-an-output-from-optim-with-a-hessian-matrix-how-to-calculate-paramet
fit <- dogll
fisher_info<-solve(-fit$hessian)
prop_sigma<-sqrt(diag(fisher_info))
prop_sigma<-diag(prop_sigma)
upper<-fit$par+1.96*prop_sigma
lower<-fit$par-1.96*prop_sigma
interval<-data.frame(value=fit$par, upper=upper, lower=lower)
interval
```


```{r,fig.height=3,fig.width=5}
h <- dogll$par[1]
r <- dogll$par[2]

# relation plot
# plus maximum likelihood fit (t=age | estimated parameters)
ggplot(dog,aes(age,p)) +
  geom_point() +
  stat_function(fun=function(age){h/(r+h)*(1-exp(-(r+h)*age))})
```


### profile

```{r}
# https://freakonometrics.hypotheses.org/20573
set.seed(1)
x=exp(rnorm(100))

log_lik=function(theta){
  a=theta[1]
  b=theta[2]
  logL=sum(log(dgamma(x,a,b)))
  return(-logL)
}

optim(c(1,1),log_lik)

prof_log_lik=function(a){
  b=(optim(1,function(z) -sum(log(dgamma(x,a,z)))))$par
  return(-sum(log(dgamma(x,a,b))))
}

vx=seq(.5,3,length=101)
vl=-Vectorize(prof_log_lik)(vx)
optim(1,prof_log_lik)

plot(vx,vl,type="l")
abline(v=optim(1,prof_log_lik)$par,lty=2)
abline(h=-optim(1,prof_log_lik)$value)
abline(h=-optim(1,prof_log_lik)$value-qchisq(.95,1)/2)
 
#segments(F$estimate[1]-1.96*F$sd[1],-170,F$estimate[1]+1.96*F$sd[1],-170,lwd=3,col="blue")
#borne=-optim(1,prof_log_lik)$value-qchisq(.95,1)/2
#(b1=uniroot(function(z) Vectorize(prof_log_lik)(z)+borne,c(.5,1.5))$root)
##[1] 1.095726
#(b2=uniroot(function(z) Vectorize(prof_log_lik)(z)+borne,c(1.25,2.5))$root)
##[1] 1.811809
```

```{r}
# log likelihood profile
dog %>% 
  mutate(max_lk={h/(r+h)*(1-exp(-(r+h)*age))},
         log_lk={sum( - (k)*log(p) - (n-k)*log(1-p) )}) %>% 
  ggplot(aes(age,max_lk)) +
  geom_line()
```


## data: one constant estimate

```{r}
# data from Table 2 of Williams 1994
dog <- data.frame(
age=c(3.71,10.76,21.00,38.89,64.07,106.82),
n=c(100,74,114,110,55,27),
k=c(14,30,63,59,37,14)
)

library(tidyverse)
dog <- dog %>% mutate(p= k/n)

#?optim
# MLE solution
dogllc <- optim(c(0.1),fn=Lccm1c,r=0.030,data=dog,hessian=TRUE)
dogllc
#summary(dogll)
```

```{r,eval=FALSE}
#https://stats.stackexchange.com/questions/27033/in-r-given-an-output-from-optim-with-a-hessian-matrix-how-to-calculate-paramet
fit <- dogllc
fisher_info<-solve(-fit$hessian)
prop_sigma<-sqrt(diag(fisher_info))
prop_sigma<-diag(prop_sigma)
upper<-fit$par+1.96*prop_sigma
lower<-fit$par-1.96*prop_sigma
interval<-data.frame(value=fit$par, upper=upper, lower=lower)
interval
```


```{r,fig.height=3,fig.width=5}
h <- dogllc$par[1]
r <- 0.03#dogll$par[2]
ggplot(dog,aes(age,p)) +
  geom_point() +
  stat_function(fun=function(age){h/(r+h)*(1-exp(-(r+h)*age))})
```

## data: change point in history